# Generated by Django 4.2 on 2025-12-31 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tarjeta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria'),
        ),
    ]
