# Generated by Django 4.2 on 2026-01-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
        ('ventas', '0002_venta_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_detalle', to='combos.combo', verbose_name='Combo'),
        ),
    ]
