# Generated by Django 4.2 on 2026-03-06 02:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        ('ventas', '0003_detalleventa_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Pagado')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_venta', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'pagos_venta',
                'ordering': ['venta'],
            },
        ),
    ]
