# Generated by Django 4.2 on 2026-03-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pagoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Tarjeta Debito', 'Tarjeta Debito'), ('Tarjeta Credito', 'Tarjeta Credito'), ('Daviplata', 'Daviplata'), ('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia'), ('Transferencia', 'Transferencia'), ('Mixto', 'Mixto'), ('Otro', 'Otro')], default='Efectivo', max_length=50, verbose_name='Método de Pago'),
        ),
    ]
