# Generated by Django 4.2 on 2026-03-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        ('ventas', '0005_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tarjeta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria'),
        ),
    ]
