# Generated by Django 4.2 on 2026-01-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_producto_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Combo')),
                ('activo', models.BooleanField(default=True, verbose_name='Combo Activo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'db_table': 'combos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('precio_combo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Especial en Combo')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad del Producto en Combo')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_combo', to='combos.combo', verbose_name='Combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combos', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto en Combo',
                'verbose_name_plural': 'Productos en Combos',
                'db_table': 'producto_combo',
                'ordering': ['combo', 'producto'],
                'unique_together': {('combo', 'producto')},
            },
        ),
    ]
