# Generated by Django 4.2 on 2026-03-20 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_proveedor'),
        ('categoria', '0001_initial'),
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productocombo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productocombo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combos', to='categoria.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productocombo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combos', to='productos.producto', verbose_name='Producto'),
        ),
    ]
