# Generated by Django 4.2 on 2025-10-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        ('clientes', '0002_remove_cliente_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargosNoRegistrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Cargo')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Transacción')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_noregistrados', to='clientes.cliente', verbose_name='Cliente (opcional)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_noregistrados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_noregistrados', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria')),
            ],
            options={
                'verbose_name': 'Cargo No Registrado',
                'verbose_name_plural': 'Cargos No Registrados',
                'db_table': 'cargosnoregistrados',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
