# Generated by Django 4.2 on 2025-10-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('inventarioproducto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='productos.producto'),
        ),
    ]
