# Generated by Django 4.2 on 2025-10-24 02:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tarjeta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('pan', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)], verbose_name='Numero de Tarjeta')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta Bancaria',
                'verbose_name_plural': 'Tarjetas Bancarias',
                'db_table': 'tarjetas_bancarias',
            },
        ),
    ]
