# Generated by Django 4.2 on 2025-10-26 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjetabancaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilidadOcasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Utilidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la Utilidad')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación de la Utilidad')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilidades_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilidades_generadas', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria')),
            ],
            options={
                'verbose_name': 'Utilidad Ocasional',
                'verbose_name_plural': 'Utilidades Ocasionales',
                'db_table': 'utilidadocasional',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
