# Generated by Django 4.2 on 2025-10-29 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de ganancia (%)')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta final')),
                ('codigo_busqueda', models.CharField(max_length=100, unique=True, verbose_name='Código de búsqueda')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=productos.models.upload_to_unique)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categoria.categoria')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='subcategoria.subcategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
    ]
