# Generated by Django 4.2 on 2025-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
