# Generated by Django 4.2 on 2025-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(default='U', max_length=50, verbose_name='Genero'),
        ),
    ]
