# Generated by Django 4.2 on 2025-12-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_descripcion'),
        ('productos', '0003_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_suministrados', to='proveedores.proveedor'),
        ),
    ]
