# Generated by Django 4.2 on 2025-10-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('contador', 'Contador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
