# Generated by Django 4.2 on 2025-11-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('codigo_venta', models.CharField(max_length=50, verbose_name='Código de la Venta')),
                ('producto_id', models.IntegerField(verbose_name='ID del Producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Devuelta')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
