# Generated by Django 4.2 on 2025-12-09 11:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0002_proveedor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('numero_orden', models.CharField(help_text='Número único de la orden de compra', max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_transito', 'En Tránsito'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total de la Orden')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_proveedor_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Proveedor',
                'verbose_name_plural': 'Órdenes de Proveedor',
                'db_table': 'ordenes_proveedor',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('producto_id', models.IntegerField(db_index=True, help_text='ID del producto desde el sistema de inventario', verbose_name='ID del Producto')),
                ('nombre', models.CharField(help_text='Nombre del producto al momento de la compra', max_length=200, verbose_name='Nombre del Producto')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Compra Unitario')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('notas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas del Producto')),
                ('orden_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.ordenproveedor', verbose_name='Orden de Proveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ordenes', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
                'db_table': 'ordenes_proveedor_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenproveedordetalle',
            index=models.Index(fields=['orden_proveedor', 'producto_id'], name='ordenes_pro_orden_p_290c41_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproveedordetalle',
            index=models.Index(fields=['proveedor'], name='ordenes_pro_proveed_798b47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenproveedordetalle',
            unique_together={('orden_proveedor', 'producto_id')},
        ),
        migrations.AddIndex(
            model_name='ordenproveedor',
            index=models.Index(fields=['proveedor', 'estado'], name='ordenes_pro_proveed_344458_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproveedor',
            index=models.Index(fields=['numero_orden'], name='ordenes_pro_numero__88de04_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproveedor',
            index=models.Index(fields=['fecha_orden'], name='ordenes_pro_fecha_o_4d0678_idx'),
        ),
    ]
