# Generated by Django 4.2 on 2025-12-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        ('proveedores', '0003_ordenproveedor_ordenproveedordetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproveedor',
            name='tarjeta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_proveedor', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria'),
        ),
        migrations.AlterField(
            model_name='ordenproveedor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'En Cotización'), ('confirmada', 'Pagada'), ('en_transito', 'En Tránsito'), ('recibida', 'Inventariada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
