# Generated by Django 4.2 on 2025-10-24 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Gasto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Tipo de Gasto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_gastos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Maestro',
                'verbose_name_plural': 'Gastos Maestros',
                'db_table': 'gastos_maestros',
            },
        ),
        migrations.CreateModel(
            name='RelacionarGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('total_gasto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del Gasto')),
                ('descripcion', models.TextField(verbose_name='Descripción Específica del Gasto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_gastos_creados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_relacionados', to='gastos.gasto', verbose_name='Tipo de Gasto (Maestro)')),
            ],
            options={
                'verbose_name': 'Registro de Gasto',
                'verbose_name_plural': 'Registros de Gastos',
                'db_table': 'registros_gastos',
                'ordering': ['-created_at'],
            },
        ),
    ]
