# Generated by Django 4.2 on 2025-10-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjetabancaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_remove_cliente_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación Lógica')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la Transacción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Pago')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Transacción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='tarjetabancaria.tarjetabancaria', verbose_name='Tarjeta Bancaria')),
            ],
            options={
                'verbose_name': 'Recepción de Pago',
                'verbose_name_plural': 'Recepciones de Pago',
                'db_table': 'recepciones_pago',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
