# Generated by Django 4.2 on 2025-10-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcionpago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recepcionpago',
            table='recepcionespago',
        ),
    ]
